### ISSUE TITLE
JPLIST MYSQL JOINS MULTIPLE TABLES WITH WHERE CLAUSE

### ISSUE THREAD

**Issue by shariq619** [no81no/jplist#173]
I am trying to do this in

server/domain/server.php

protected function getData(){
			
			$items = null;

$query = "SELECT registration.*,login.* FROM " . DB_TABLE . "  LEFT JOIN login ON registration.company_id = login.company_id where login.approve = 3 ";

Without where clause this query working fine.

Can anyone tell me how to use where clause in JPLIST PHP MYSQL.

**Comment by PJanisio** [comment]
I think this is the place where complete query is formulated, so you can add AND clause inside " " brackets, but i dont know if this will work as filtering and paginating will add his own clauses. Didnt tested it.

It could be good to create possibility for users to create custom query and add possibility to fetch from multiple tables. Because now the only solution is to merge the data in one table in mysql.

```php
if($this->filter->filterQuery){				
				$query .= " " . $this->filter->filterQuery . " ";
			}
				
			//get queries / fields				
			if($this->sorting->sortQuery){
				$query .= " " . $this->sorting->sortQuery . "  ";
			}
							
			if($this->pagination->paginationQuery){
				$query .= " " . $this->pagination->paginationQuery . "  ";
			}
```

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#15
